### ISSUE TITLE
RarInfo not agreeing with parameters needed to pass to the extraction step; use libunrar instead of running command-line unrar, and non-unicode filenames

### ISSUE THREAD

**Issue by HinTak** [markokr/rarfile#28] opened 2016-12-01 21:33 UTC
RarInfo not agreeing with parameters needed to pass to the extraction step seem to defeat the purpose of looking at RarInfo  first.

Use libunrar instead of running command-line unrar for non-unicode filenames might be the answer.

I have a rar file which seems to have been generated on localised CJK windows system (i.e. filenames are multi-byte but non-unicode).

RarInfo.filename gives the following hexdumps with ` ' '.join(["%04X"% ord(x) for x in info.filename])`

```
E5A4 A9B9 72A6 ACAB
E5A4 A9B9 72A6 ACAB 535C 4E49 3030 504D 542E 4654
00A4 00E5 00B9 00A9 00A6 0072 00AB 00AC 005C 0057 0045 0049 0030 0030 0042 002E 0054 0054 0046
```

rarfile seems to interprete the data as UTF16-LE  or latin1, but in fact it is BIG5 (and big-endian - higher-byte of big5 encoding first). You can see the 3rd item is padded and byte-swapped compared to the others.

I also don't know why rarfile is behaving inconsistently - one file is in latin1, but all the others are in UTF16-LE, in the same archive.

Anyway, I have two problems:

command-line unrar munches the paths - in the name of 'security measure', it would not extract filename as they were, or even list them as rawbytes, but insists that they are unicode and insert a lot of '0xE0' with private encoding in the path names when the byte ranges is outside unicode descriptions. (see `unrar/unicode.cpp` in unrar's source).

And you are running unrar the command line, which means there is no hope of matching the `RarInfo.filename` with what is required on the command line (to extract then rename), since `RarInfo.filename` contains raw non-unicode multibyte date, while command line wants corrupted unicode data.

FWIW, `lsar -e BIG5 ...` seems to do the right thing. But I just like `python-rarfile` to be able to do that, and give me more control of examining and extracting the files individually.

RarInfo not agreeing with parameters needed to pass to the extraction step seem to defeat the purpose of looking at RarInfo  first.

**Comment by markokr** [comment] 2019-09-20 17:12
Please try with Python 3.6+ which switched from ANSI Windows APIs to UTF16 APIs.

If the problem is still there then please reopen the bug.

**Comment by HinTak** [comment] 2019-09-23 09:56
This issue is about extracting files on unix correctly, which are compressed on windows under a non-unicode multibyte locale. 

Nothing to do with running windows python.

**Comment by HinTak** [comment] 2019-09-23 10:00
@markokr does not make the option to re-open. Have you disabled that functionality?

**Comment by markokr** [comment] 2019-09-23 17:15
Well, I do see the button.

**Comment by markokr** [comment] 2019-09-23 17:55
If the issue is reproducable on Linux it's more interesting,
although old OEM codecs are not high priority.

You could workaround it by bumping HACK_SIZE_LIMIT to always
activate, that way you dont need to use filenames with unrar.
But it won't work on split/solid/password-protected archives.

The charset= was supposed to help, but it does only visually,
it does not help much with unrar.

Please try following things:

- Give orig_filename as bytes() to Popen that calls unrar.
  This should work on Python 3 to help remove Python from situation.

- Try setting LANG/LC_ALL/LC_CTYPE to C in unrar env,
  with Popen(env=)

Does doing either or both help?

**Comment by HinTak** [comment] 2019-09-24 11:33
Yes, this issue was about unrar'ing on Linux, of archive generated on multibyte non-unicode window, as far as I remember. I'll need to find the actual file, or look for equivalent elsewhere.

I'll let you know when I find the archive - it has been 3 years...

**Comment by markokr** [comment] 2020-07-19 17:54
Not reproducable, closing.

**Closed by markokr** 2020-07-19 17:54 UTC
